Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy

In [3]:
import numpy as np

# Create a 1D numpy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int64


In [6]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) # 1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [8]:
# 2D numpy array 

arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [9]:
np.arange(0, 10, 2) # start, stop, step

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Attributes of Numpy array|
print("Array: \n", arr) 
print("Shape: ", arr.shape) # Output: Shape: (2, 3)
print("Number of dimensions: ", arr.ndim) # Output: Number of dimensions: 2 
print("Size: ", arr.size) # Output: Size: 6 
print("Data type: ", arr.dtype) # Output: Data type: int64(may vary based on the system)
print("Item size(in bytes): ", arr.itemsize) # Output: Item size(in bytes): 8(may vary based on the system)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size:  6
Data type:  int64
Item size(in bytes):  8


In [17]:
## Numpy Vectorized Operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
print("Addition: ", arr1 + arr2)

# Element-wise subtraction
print("Subtraction: ", arr1 - arr2)

# Element-wise multiplication
print("Multiplication: ", arr1 * arr2)

# Element-wise division
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [18]:
## Universal Functions

arr = np.array([1, 2, 3, 4, 5])

# Square root of each element
print("Square root: ", np.sqrt(arr))

# Exponential of each element
print("Exponential: ", np.exp(arr))

# Sine of each element
print("Sine: ", np.sin(arr))

# natural logarithm of each element
print("Natural logarithm: ", np.log(arr))

Square root:  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [19]:
## Array Slicing and Indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr[0]

array([1, 2, 3, 4])

In [23]:
print(arr[0][0])

1


In [27]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [28]:
print(arr[0:2, 2:])

[[3 4]
 [7 8]]


In [29]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [30]:
## Modify array elements
arr[0, 0] = 100
print("Modified array: \n", arr)

Modified array: 
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:] = 100
print("Modified array: \n", arr)

Modified array: 
 [[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [32]:
## Statistical Concepts - Normalization
# to have a mean of 0 and a standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [33]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)   

# Median
median = np.median(data)
print("Median: ", median)

# Standard deviation
std_dev = np.std(data)
print("Standard deviation: ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard deviation:  2.8722813232690143
Variance:  8.25


In [36]:
## Logical Operations

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [39]:
data[(data > 5) & (data < 8)]

array([6, 7])