Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy

In [3]:
import numpy as np

# Create a 1D numpy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int64


In [6]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) # 1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [8]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
